const EMBEDDED_SHEET_CSV = `
ace,えーす
actor,はいゆう
actress,じょゆう
adult,おとな
air,くうき
airplane,ひこうき
airport,くうこう
alarm,めざましどけい
album,あるばむ
almond,あーもんど
alpha,あるふぁ
alphabet,あるふぁべっと
am,ごぜん
america,あめりか
anchor,いかり/あなうんさー
and,あんど
angel,てんし
anger,いかり
angle,かく
animal,どうぶつ
ant,あり
apartment,あぱーと/まんしょん
apple,りんご
april,うづき/しがつ
aquarium,すいそう/すいぞくかん
arena,ありーな
arm,うで
army,ぐん/ぐんたい
arrow,や/やじるし
art,げいじゅつ
artist,えかき
atm,えーてぃーえむ
august,はちがつ/はづき
aunt,おば
autumn,あき
average,へいきん
baby,あかちゃん/あかんぼう
back,せなか
badge,ばっじ/ばっぢ
bag,かばん/ふくろ
ball,たま/ぶとうかい/まり
balloon,ききゅう/ばるーん/ふうせん
bamboo,たけ
banana,ばなな
band,おび
bank,ぎんこう
bar,のべぼう/ばー
barcode,ばーこーど
base,べーす
baseball,べーすぼーる/やきゅう
basket,ばすけっと/かご
basketball,ばすけ/ばすけっとぼーる
bass,べーす
bat,こうもり
bath,おふろ/ふろ
batter,ばったー
battery,かんでんち/でんち
bay,わん/いりえ
bbq,ばーべきゅー
beach,はま/はまべ/びーち/かいがん/うみ
beaf,ぎゅうにく/びーふ
beak,くちばし
beam,びーむ
bean,まめ
bear,くま
beast,どうぶつ/けもの
beauty,びじん
bed,べっど
bee,みつばち/はち
beer,びーる
bell,すず/べる/かね
belt,べると
bench,べんち
beta,べーた
bicycle,じてんしゃ
bike,ばいく
bill,おさつ/ふだ
billiion,じゅうおく
bingo,びんご
bird,とり
birthday,たんじょうび
black,くろ/くろいろ
blank,くうはく/くうらん
blanket,もうふ
blind,すだれ
block,ぶろっく
blood,けつえき/ち
blue,あお/あおいろ
blueberry,ぶるーべりー
boar,いのしし
board,いた/ぼーど
boat,ぼーと
body,したい/からだ
bomb,ばくだん
bond,ぼんど
bone,ほね
book,ほん
bottle,すいとう/びん
bottom,そこ
bow,ゆみ
bowl,うつわ/おじぎ/ちゃわん/どんぶり/ぼうる
bowling,ぼうりんぐ
box,はこ/ぼっくす
boxer,ぼくさー
boxing,ぼくしんぐ
boy,おとこのこ/しょうねん/だんし/ぼーい
boyfriend,かれし/おとこともだち
brain,のう/のうみそ
bread,ぱん
breakfast,ちょうしょく
breath,いき
bridge,はし
bronze,どう
brother,あに/おとうと
brown,ちゃいろ/ちゃ
brush,えふで/はけ/ふで/ぶらし
bubble,あわ/ばぶる
bucket,ばけつ/おけ
bug,むし
building,びる
bulldog,ぶるどっぐ
bunny,うさぎ
bus,ばす
butter,ばたー
butterfly,ちょう/ちょうちょ/ちょうちょう/ばたふらい
buttery,ばってりー
button,ぼたん
cabbage,きゃべつ
cable,けーぶる
cafe,かふぇ/きっさ/きっさてん
cake,けーき
calendar,こよみ
calender,かれんだー/こよみ
camel,らくだ
camera,かめら
cameraman,かめらまん
camp,きゃんぷ
campus,きゃんばす
can,かん/かんづめ
canada,かなだ
candle,きゃんどる/ろう/ろうそく
candy,きゃんでぃ/きゃんでぃー/きゃんでー/あめ
cannon,たいほう
canoe,かぬー
cap,ぼうし
captain,せんちょう
car,くるま/じどうしゃ
caramel,きゃらめる
card,かーど
carpet,かーぺっと/じゅうたん
carrot,きゃろっと/にんじん
cart,かーと
case,けーす/うつわ
cash,かね/げんきん
castle,しろ
cat,ねこ
catch,きゃっち/きゃっちぼーる
catcher,きゃっちゃー
cd,しーでぃー
cello,ちぇろ
cellphone,けいたい/けいたいでんわ
center,せんたー
chain,くさり/ちぇーん/ちぇいん
chair,いす/ざいす/ちぇあ/ちぇあー
charge,じゅうでん
checkbox,ちぇっくぼっくす
cheese,ちーず
cheesecake,ちーずけーき
cherry,さくらんぼ/ちぇりー
chess,ちぇす
chicken,ちきん/とりにく/にわとり
child,こども
children,こども
china,ちゅうごく
chip,ちっぷ
chips,ぽてとちっぷす
chocolate,ちょこ/ちょこれーと
chopstick,はし
chopsticks,さいばし/はし
chorus,がっしょう
christmas,くりすます
church,きょうかい
cider,さいだー
cinema,えいが
circle,えん/さーくる/まる
circus,さーかす
city,し
class,じゅぎょう
classroom,きょうしつ
clip,くりっぷ
clock,とけい
closet,おしいれ
cloud,くも
clover,くろーばー
club,くらぶ
coat,こーと
cocoa,ここあ
coffee,こーひー
coin,こいん/こうか
cola,こーら
cold,さむけ/かぜ
college,だいがく
color,いろ
comic,こみっく/まんが
company,かいしゃ
compass,こんぱす/ほういじしゃく/ほういじしん/らしんばん
computer,ぱそこん/こんぴゅーたー/こんぴゅーた
contact,こんたくと
controller,こんとろーら/こんとろーらー
cookie,くっきー
cooking,くっきんぐ/りょうり
cooler,くーらー
copy,もしゃ/こぴー
corn,こーん/とうもろこし
counter,かうんたー
country,くに
couple,かっぷる/ふうふ
cover,うらびょうし/かばー/ひょうし
cow,うし
crab,かに
cracker,くらっかー
cream,くりーむ
cross,じゅうじ/じゅうじか/ばつ
crow,からす
crown,おうかん/かんむり
cup,かっぷ/こっぷ
curry,かれー
curve,きょくせん
customer,きゃく
cutter,かったー
cycling,さいくりんぐ
dam,だむ
dance,おどり/だんす/ぶよう
dancer,だんさー
dark,やみ
date,でーと
daughter,むすめ
day,ひ
death,しにがみ/し/しぼう
december,じゅうにがつ/しわす
deer,しか
delivery,でまえ
delta,でるた
desk,つくえ/ですく
detective,たんてい
devil,あくま
dial,だいある/だいやる
diary,えにっき/にっき
dice,さいころ/だいす
dictionary,じしょ/じてん
dinner,ゆうしょく
disc,でぃすく
dish,さら
disk,えんばん/でぃすく
display,でぃすぷれい
diver,あま
diving,だいびんぐ
dj,でぃーじぇー/でぃすくじょっきー
doctor,いしゃ/どくたー/はかせ/はくし/いし
dog,いぬ
doll,にんぎょう
dollar,どる
dolphin,いるか
dome,どーむ
domino,どみの
donut,どーなつ/どーなっつ
door,と/どあ/とびら
dot,てん/どっと
double,だぶる
down,した
dragon,どらごん/りゅう
drama,しばい
draw,あいこ
dream,ゆめ
dress,どれす
dressing,どれっしんぐ
drink,どりんく
drive,どらいぶ
driver,うんてんし/うんてんしゅ/どらいばー
driving,うんてん
drug,やくぶつ/くすり/やくひん
drugstore,やっきょく
drum,たいこ/どらむ/どらむかん
drummer,どらまー
dvd,でぃーぶいでぃー
eagle,わし
ear,みみ
earth,あーす/ちきゅう
earthquake,じしん
east,ひがし
egg,たまご
eight,はち
eighteen,じゅうはち
eighty,はちじゅう
elbow,ひじ
elephant,ぞう
eleven,じゅういち
email,でんしめーる
enemy,てき
engine,えんじん
english,えいご
envelope,ふうとう
equal,いこーる/とうごう
eraser,けしごむ
escape,だっしゅつ/とうぼう
euro,ゆーろ
even,ぐうすう
evening,ゆうがた/ゆうやけ
event,ぎょうじ
exit,でぐち
eye,め
face,かお
factory,こうじょう
fail,しっぱい
failure,しっぱい
fairy,ようせい
fall,あき/たき
family,かぞく
fan,うちわ/おうぎ/せんす/せんぷうき/ふぁん
fashion,ふぁっしょん
father,ちち/ちちおや/ぱぱ
fax,ふぁっくす
feather,はね
february,きさらぎ/にがつ
female,おんな/じょせい/めす
festival,まつり
fever,はつねつ
field,はたけ
fifteen,じゅうご
fifty,ごじゅう
fight,けんか/せんとう
fighter,かくとうか
film,ふぃるむ
final,けっしょう
finger,ゆび
fire,かじ/ひ
first,ふぁーすと/いちばんめ
fish,さかな
fishing,つり/ふぃっしんぐ
five,ご
flag,はた
flash,せんこう
flat,ふらっと
floor,ゆか
flower,ふらわー/はな
folder,ふぉるだ/ふぉるだー
food,めし/しょくじ
foot,あし/ふっと
football,ふっとぼーる
footbath,あしゆ
forest,はやし/もり
fork,ふぉーく
forty,よんじゅう
four,し/よん
fourteen,じゅうし
fox,きつね
frame,わく/ふれーむ
friday,きんよう/きんようび
friend,ふれんど/ともだち/とも/ゆうじん
frog,かえる
fruit,くだもの/ふるーつ
fruits,くだもの/ふるーつ
fullmoon,まんげつ
gallery,ぎゃらりー
gamble,とばく/ばくち
game,げーむ
garden,にわ
gardening,がーでにんぐ
gas,がす
gate,もん
gear,ぎあ/はぐるま
gem,ほうせき
genius,てんさい
gentleman,しんし
ghost,おばけ/ゆうれい/ようかい
gift,ぎふと/おくりもの
ginger,しょうが
girl,おんなのこ/がーる/しょうじょ/じょし/おんな
girlfriend,かのじょ/おんなともだち
glass,がらす/ぐらす
glasses,めがね
glove,ぐろーぶ/てぶくろ
gloves,てぶくろ
goal,ごーる
goalkeeper,ごーるきーぱー
goat,やぎ
god,かみ/かみさま
gold,きん/きんいろ/ごーるど
golf,ごるふ
gorilla,ごりら
graduation,そつぎょう
grape,ぶどう
grapefruit,ぐれーぷふるーつ
grass,くさ/しば/しばふ
gray,はい/はいいろ
green,みどり/みどりいろ
group,むれ
guitar,ぎたー
guitarist,ぎたりすと
gum,がむ/はぐき
gun,じゅう/てっぽう
gym,じむ/たいいくかん
hair,かみのけ/かみ
half,はーふ
hall,ほーる
halloween,はろうぃん/はろうぃーん
ham,はむ
hamburger,はんばーがー
hammer,かなづち/とんかち/はんまー
hand,て
handle,とって/はんどる
handshake,あくしゅ
hanger,はんがー
harp,はーぷ
hat,はっと/ぼうし
hawk,たか
head,あたま/せんとう
heart,しんぞう/はーと
heat,ねつ
heater,だんぼう/ひーたー
heaven,てんごく
heel,かかと
helicopter,へり/へりこぷたー
hell,じごく
helmet,かぶと/へるめっと/めっと
hero,ひーろー/えいゆう
hexagon,ろっかくけい
hiking,はいきんぐ
hill,おか
hip,しり
hiphop,ひっぷほっぷ
hockey,ほっけー
hole,あな/ほーる
home,ほーむ/いえ
homeless,ほーむれす
honey,はちみつ
horizon,すいへいせん/ちへいせん
horn,つの
horse,うま
hospital,びょういん
host,しかい/ほすと
hotel,ほてる
house,いえ/はうす
human,にんげん/ひと
hundred,ひゃく
hunter,かりうど/かりゅうど/はんたー/りょうし
hurdle,はーどる
husband,おっと
ice,あいす/こおり
idol,あいどる
illustrator,いらすとれーた/いらすとれーたー
indigo,あいいろ
infinity,むげん/むげんだい
ink,いんく/すみ
insect,むし
internet,いんたーねっと
interview,いんたびゅー/めんせつ/もんしん
interviewer,めんせつかん/いんたびゅあー
iron,あいろん/てつ
island,しま
jack,じゃっく
jacket,じゃけっと
jam,じゃむ
january,いちがつ/むつき
japan,にほん
japanese,にほんご
jazz,じゃず
jelly,ぜりー
jet,じぇっとき/じぇっと
jewel,ほうせき
joker,じょーかー
joy,よろこび
juice,じゅーす/しる
july,しちがつ/ふみづき
jump,じゃんぷ
june,みなづき/ろくがつ
jungle,じゃんぐる
jupiter,もくせい
key,かぎ/きー
keyboard,きーぼーど/けんばん
keyholder,きーほるだー
kick,きっく
kid,こども
king,おう/おうさま/きんぐ
kiss,きす/くちづけ/せっぷん
kitchen,きっちん/だいどころ
knife,ないふ/ほうちょう
knight,きし/ないと
knock,のっく
korea,かんこく
label,らべる
lady,じょせい/おんな
lake,みずうみ
lamp,らんぷ
leaf,おちば/はっぱ/は
led,えるいーでぃー
left,ひだり
leg,あし/すね
lemon,れもん
letter,てがみ/ふみ
library,としょかん/としょしつ/らいぶらり/らいぶらりー
lift,りふと
light,あかり/ひかり/らいと/しょうめい
lily,ゆり
line,かいせん/せん/れつ/ぎょうれつ
lion,しし/らいおん
lip,くちびる/りっぷ
list,りすと
live,らいぶ
lock,じょう/じょうまえ/ろっく
locker,ろっかー
lose,まけ
love,あい/らぶ/こい
lunch,ちゅうしょく/らんち
machine,きかい
magazine,ざっし
magic,てじな/まじっく
magician,てじなし/まじしゃん
magnet,じしゃく
maid,めいど
mail,ゆうそう
mailbox,ゆうびんうけ
male,おとこ/だんせい/おす
man,おとこ/だんせい
manager,まねーじゃ/まねーじゃー
map,ちず
march,こうしん/さんがつ
market,いちば/しじょう
mars,かせい
mask,おめん/かめん/ますく
massage,まっさーじ
mat,まっと
match,まっち
math,すうがく
max,さいだい
may,ごがつ/さつき
maze,めいろ
mc,しかい/ぱーそなりてぃ/ぱーそなりてぃー/えむしー
measure,めじゃー
meat,にく
medal,めだる
medicine,くすり
melon,うり/めろん
memo,めも
memory,おもいで
men,だんせい
mercury,すいせい
mermaid,にんぎょ
message,めっせーじ
milk,ぎゅうにゅう/みるく
million,ひゃくまん
min,さいしょう
minus,ひく/ふ/まいなす
minute,ふん
mirror,かがみ/すがたみ/みらー
mist,みすと/きり
monday,げつよう/げつようび/まんでー
money,かね
monitor,もにた/もにたー
monkey,さる
monster,かいぶつ/もんすたー
moon,つき
morning,あさ
mother,はは/ははおや/まま
motor,もーたー
mountain,やま
mouse,ねずみ/まうす
mouth,くち
movie,えいが
museum,はくぶつかん
mushroom,きのこ/まっしゅるーむ
music,おんがく
musical,みゅーじかる
musician,おんがくか/みゅーじしゃん
name,なまえ
nation,くに
navy,こん/こんいろ
neck,くび
necklace,ねっくれす/くびわ
necktie,ねくたい
needle,はり
neet,にーと
nephew,おい
neptune,かいおうせい
net,あみ/ねっと
news,にゅーす
newscaster,あなうんさー
newspaper,しんぶん/しんぶんし
ng,えぬじー
niece,めい
night,よる
nine,きゅう/く
nineteen,じゅうく/じゅうきゅう
ninety,きゅうじゅう
no,いいえ
noodle,めん
noon,しょうご/ひる
north,きた
nose,はな
note,おんぷ/のーと
notebook,のーとぶっく/のーと
novel,しょうせつ
november,しもつき/じゅういちがつ
number,かず/すうじ
nurse,かんごし/かんごふ/なーす
nut,なっつ
nuts,あーもんどなっつ/なっつ
oasis,おあしす
ocean,うみ
october,かんなづき/じゅうがつ
octopus,たこ
odd,きすう
off,おふ
office,おふぃす
oil,あぶら/おいる
ok,おーけー
okay,おーけー
olive,おりーぶ
olympic,おりんぴっく/ごりん
olympics,おりんぴっく/ごりん
on,おん
one,いち
onion,たまねぎ
open,おーぶん/かいてん
orange,おれんじ/だいだい/みかん
othello,おせろ
oven,かま/おーぶん
owl,ふくろう
pack,ぱっく
page,ぺーじ
paint,えのぐ/ぺんき
pair,こんび/ぺあ
pajama,ねまき/ぱじゃま
pajamas,ねまき/ぱじゃま
pancake,ぱんけーき/ほっとけーき
panda,ぱんだ
panel,ぱねる
pansy,ぱんじー
pants,ずぼん/ぱんつ
paper,ぱー/ぺーぱー/かみ
parent,おや
parents,ふけい/りょうしん
park,こうえん
parking,ちゅうしゃ/ちゅうしゃじょう/ぱーきんぐ
parrot,おうむ
partition,ぱーてぃしょん/ぱーてーしょん
party,ぱーてぃー
pass,ごうかく/ぱす
passport,ぱすぽーと
pause,いちじていし
pc,ぱそこん
peace,ぴーす
peach,ぴーち/もも
pear,なし/ようなし
pedal,ぺだる
pen,ぺん
pencil,えんぴつ
penguin,ぺんぎん
pepper,こしょう
percent,ぱーせんと
phone,でんわ/でんわき
photo,しゃしん
pianist,ぴあにすと
piano,ぴあの
picnic,ぴくにっく
picture,え/かいが
pie,えんぐらふ/ぱい
piece,ぴーす/はへん
pig,ぶた
pilot,ぱいろっと
pin,ぴん/がびょう
pine,まつ
pineapple,ぱいなっぷる
pink,ぴんく/ぴんくいろ/ももいろ
pipe,ぱいぷ
pirate,かいぞく
pitcher,ぴっちゃー
pizza,ぴざ
plane,ひこうき
planet,わくせい
play,しばい/ぷれー
player,せんしゅ
plus,たす/ぷらす
pm,ごご
pocket,ぽけっと
poison,どく
poker,ぽーかー
police,けいさつ
pool,ぷーる
poolside,ぷーるさいど
pork,ぶたにく/ぽーく
post,ぽすと
postcard,えはがき/はがき/ぽすとかーど
poster,ぽすたー
pot,かま/なべ/ぽっと/はち
potato,いも/じゃがいも/ぽてと
powder,こな
present,ぷれぜんと
price,ねだん/かかく
prince,おうじ/おうじさま
princess,おうじょ/ひめ/ひめさま/ぷりんせす
printer,ぷりんた/ぷりんたー
prison,ろうや
programmer,ぷろぐらま/ぷろぐらまー
projecter,ぷろじぇくた/ぷろじぇくたー
proof,しょうめい
pumpkin,かぼちゃ/ぱんぷきん
punch,ぱんち
purple,むらさき/むらさきいろ
puzzle,ぱずる
qr,きゅーあーる
queen,くいーん/じょおう
question,くえすちょんまーく/はてな
quiz,くいず
rabbit,うさぎ
race,れーす
racket,らけっと
radio,らじお
rain,あめ
rainbow,にじ
raincoat,れいんこーと
ranking,らんきんぐ
rap,らっぷ
rat,ねずみ
reading,どくしょ
recycle,りさいくる
red,あか/あかいろ
reporter,きしゃ
restaurant,れすとらん
rice,ごはん/こめ/めし
riddle,なぞ
right,みぎ
ring,ゆびわ/りんぐ/わ
river,かわ
road,どうろ/みち/しゃどう
robot,ろぼ/ろぼっと
rock,いわ/ぐー/ろっく
rocket,ろけっと
roof,やね
room,へや
root,ね/ねっこ
rope,つな/なわ/ろーぷ
rose,ばら
row,れつ
ruler,じょうぎ
safe,きんこ/あんぜん
salad,さらだ
salmon,さーもん
salt,しお
sand,すな
santa,さんた
saturday,どよう/どようび
saturn,どせい
scan,すきゃん
scanner,すきゃな/すきゃなー
school,がっこう
science,りか
scientist,かがくしゃ
scissors,ちょき/はさみ
score,がくふ/とくてん
screen,あみど/すくりーん
sea,うみ
seafood,かいせん/かいせんりょうり
seal,あざらし/じーんず
search,けんさく
season,きせつ
seat,しーと/せき
second,せかんど/にばんめ/びょう
seed,たね
select,せんたく
selection,せんたく
september,くがつ/ながつき
server,さーば/さーばー
seven,しち/なな
seventeen,じゅうしち/じゅうなな
seventy,ななじゅう
sex,せいべつ
shadow,かげ
shark,さめ
sharp,しゃーぷ
sheep,ひつじ
sheet,しーと/しーつ
shell,かい/かいがら
ship,ふね
shirt,しゃつ/わいしゃつ
shoe,うわばき/くつ
shoes,しゅーず/うわばき/くつ
sholder,かた
shoot,しゅーと
shop,みせ
shopping,かいもの/しょっぴんぐ
show,しょー
shower,しゃわー
shutter,しゃったー
side,わき
sign,ふごう/ひょうしき/かんばん
silver,ぎん/ぎんいろ/しるばー
singer,かしゅ
sister,あね/いもうと/しすたー
six,ろく
sixteen,じゅうろく
sixty,ろくじゅう
sketch,しゃせい/すけっち
ski,すきーいた/すきー
skin,はだ/ひふ
skip,すきっぷ
sky,そら
sl,じょうききかんしゃ
slash,すらっしゅ
sleep,すいみん
slot,すろっと
smartphone,すまーとふぉん/すまーとほん/すまふぉ/すまほ
smile,えがお/えみ
smoke,けむり
snack,すなっく/すなっくがし
snail,かたつむり/でんでんむし/まいまい
snake,へび
snow,ゆき
soccer,さっかー
sock,くつした
socks,くつした/そっくす
soda,そーだ/たんさん
sofa,そふぁ/そふぁー
son,むすこ
song,うた
sound,おと
soup,すーぷ/しる
south,みなみ
soy,だいず
soybean,えだまめ
space,うちゅう
spade,すぺーど
speaker,かくせいき/すぴーかー
speech,えんぜつ/すぴーち
spider,くも
spiral,らせん
spirit,せいれい/れい
spoon,すぷーん/れんげ
sport,すぽーつ
sports,すぽーつ
spring,ばね/はる
spy,すぱい
square,しかく/しかくけい
stage,ぶたい
stamp,きって/すたんぷ/はんこ
stand,すたんど/だい
stapler,すてーぷらー/ほちきす/ほっちきす
star,ほし
start,すたーと/かいし/はじめ/はじまり
station,えき
steam,ゆげ/じょうき
step,だんさ
stick,ぼう/すてっき
stone,いし
stop,ていし
stopwatch,すとっぷうぉっち
store,みせ
storm,あらし
strap,すとらっぷ/つりかわ
strawberry,いちご
stretch,じゅうなん/すとれっち/せのび
string,げん/ひも/いと
student,がくせい/せいと
study,がくしゅう/しょさい/べんきょう
sugar,さとう
suit,すーつ
summer,なつ
sun,たいよう
sunday,にちよう/にちようび
sunny,はれ
sunrise,ひので
sunset,ゆうぐれ/ゆうひ
supermarket,すーぱー/すーぱーまーけっと
surfboard,さーふぼーど
surfer,さーふぁー
surfing,さーふぃん/なみのり
swallow,つばめ
swan,はくちょう
sweat,あせ
sweater,せーたー
swimming,すいえい
switch,すいっち
sword,かたな/けん/たち/つるぎ
table,てーぶる/ひょう
tablet,たぶれっと
tail,お/しっぽ
tape,てーぷ
target,まと/ひょうてき
taxi,たくしー
tea,ちゃ
teacher,きょうし/せんせい
teacup,てぃーかっぷ
team,ちーむ
teapot,てぃーぽっと
tear,なみだ
teeth,は
telephone,でんわ
television,てれび
temple,しんでん/てら
ten,じゅう
tennis,てにす
tent,てんと
test,しけん/てすと
textbook,きょうかしょ
theater,えいがかん/げきじょう
third,さーど/さんばんめ
thirteen,じゅうさん
thirty,さんじゅう
thousand,せん
three,さん
thunder,いかずち/かみなり/いなずま
thursday,もくよう/もくようび
ticket,きっぷ/ちけっと
tie,たい
tiger,とら
time,とき/じかん
tobacco,たばこ
today,きょう
toilet,といれ/べんじょ
tomato,とまと
tomorrow,あした/あす
tongue,した/たん/べろ
tooth,は
top,こま/ちょうじょう
touch,たっち
tour,りょこう
tournament,とーなめんと
towel,おしぼり/たおる
tower,とう
toy,おもちゃ
train,きかんしゃ/でんしゃ/きしゃ
training,きょうしゅう/とれーにんぐ
trap,わな
travel,たび/りょこう
treasure,たから
tree,き
triangle,さんかく/さんかくけい/とらいあんぐる
trio,とりお
trip,たび/りょこう
triple,とりぷる
trump,とらんぷ
tube,くだ/ちゅーぶ/つつ
tuesday,かよう/かようび
tulip,ちゅーりっぷ
tv,てれび/てれびじょん
twelve,じゅうに
twenty,にじゅう
twin,ふたご
two,に
typewriter,たいぷらいたー
typing,たいぴんぐ
ufo,みかくにんひこうぶったい/ゆーふぉー
umbrella,かさ/あまがさ
uncle,おじ
under,した
underground,ちか
unicorn,ゆにこーん
uniform,せいふく/ゆにふぉーむ/がくせいふく
universe,うちゅう
university,だいがく
up,うえ
update,こうしん
uranus,てんのうせい
valentine,ばれんたいん
vegetable,やさい
venus,きんせい
video,びでお
village,たに
vinegar,す
viola,びおら
violet,すみれ/むらさき/むらさきいろ
violin,ばいおりん
violinist,ばいおりにすと
voice,こえ
volleyball,ばれーぼーる
walk,うぉーきんぐ/さんぽ
walking,うぉーきんぐ
wall,かべ/へい
wallet,さいふ
war,せんそう
watch,うでどけい/とけい
water,みず
watermelon,すいか
wave,なみ
weather,きしょう
wedding,けっこんしき
wednesday,すいよう/すいようび
weight,おもり/ふんどう
west,にし
whale,くじら
wheel,しゃりん/たいや
white,しろ/しろいろ
wife,つま
win,かち/しょうり
wind,かぜ/かち
window,まど
wine,わいん
wing,つばさ
wink,ういんく
winner,しょうしゃ
winter,ふゆ
wire,わいやー
witch,まじょ
wizard,まほうつかい
wolf,おおかみ
woman,おんな/じょせい
women,おんな/じょせい
wood,き/もくざい/はやし
woods,はやし
word,たんご
work,しごと/ろうどう
world,せかい
worm,むし
writer,さっか
xmas,くりすます
year,とし/ねん
yellow,きいろ/き
yes,はい
yesterday,きのう/さくじつ
zebra,しまうま
zero,れい
zipper,じっぱー/ちゃっく
zoo,どうぶつえん
zoom,かくだい`;
